"""add_preferencia_notificacao_table

Revision ID: bdcd53f6bfdb
Revises: 21c808234569
Create Date: 2025-12-23 14:00:31.583435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Identificadores de revisão usados pelo Alembic
revision: str = 'bdcd53f6bfdb'
down_revision: Union[str, None] = '21c808234569'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Aplica as mudanças da migração (upgrade).
    
    Este método é executado quando você roda:
    - alembic upgrade head (aplica todas as migrações pendentes)
    - alembic upgrade +1 (aplica a próxima migração)
    - alembic upgrade <revision> (aplica até uma revisão específica)
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preferencia_notificacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('novas_escalas', sa.Boolean(), nullable=False),
    sa.Column('escalas_atribuidas', sa.Boolean(), nullable=False),
    sa.Column('lembretes', sa.Boolean(), nullable=False),
    sa.Column('avaliacoes', sa.Boolean(), nullable=False),
    sa.Column('trocas_escalas', sa.Boolean(), nullable=False),
    sa.Column('substituicoes', sa.Boolean(), nullable=False),
    sa.Column('email', sa.Boolean(), nullable=False),
    sa.Column('push', sa.Boolean(), nullable=False),
    sa.Column('whatsapp', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_index(op.f('ix_preferencia_notificacao_id'), 'preferencia_notificacao', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Reverte as mudanças da migração (downgrade).
    
    Este método é executado quando você roda:
    - alembic downgrade -1 (reverte a última migração)
    - alembic downgrade base (reverte todas as migrações)
    - alembic downgrade <revision> (reverte até uma revisão específica)
    
    ATENÇÃO: Nem todas as operações podem ser revertidas!
    Revise sempre este método após gerar uma migração.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_preferencia_notificacao_id'), table_name='preferencia_notificacao')
    op.drop_table('preferencia_notificacao')
    # ### end Alembic commands ###
