"""add_configuracao_distrito_table

Revision ID: 21c808234569
Revises: 061c30919465
Create Date: 2025-12-23 12:06:35.360950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Identificadores de revisão usados pelo Alembic
revision: str = '21c808234569'
down_revision: Union[str, None] = '061c30919465'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Aplica as mudanças da migração (upgrade).
    
    Este método é executado quando você roda:
    - alembic upgrade head (aplica todas as migrações pendentes)
    - alembic upgrade +1 (aplica a próxima migração)
    - alembic upgrade <revision> (aplica até uma revisão específica)
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracao_distrito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('distrito_id', sa.Integer(), nullable=False),
    sa.Column('recorrencia_maxima_mes', sa.Integer(), nullable=False),
    sa.Column('intervalo_minimo_dias', sa.Integer(), nullable=False),
    sa.Column('sistema_preferencias_habilitado', sa.Boolean(), nullable=False),
    sa.Column('prazo_avaliacao_dias', sa.Integer(), nullable=False),
    sa.Column('confirmacao_obrigatoria', sa.Boolean(), nullable=False),
    sa.Column('prazo_confirmacao_horas', sa.Integer(), nullable=False),
    sa.Column('permitir_trocas', sa.Boolean(), nullable=False),
    sa.Column('aprovar_trocas_obrigatorio', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['distrito_id'], ['distrito.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('distrito_id')
    )
    op.create_index(op.f('ix_configuracao_distrito_id'), 'configuracao_distrito', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Reverte as mudanças da migração (downgrade).
    
    Este método é executado quando você roda:
    - alembic downgrade -1 (reverte a última migração)
    - alembic downgrade base (reverte todas as migrações)
    - alembic downgrade <revision> (reverte até uma revisão específica)
    
    ATENÇÃO: Nem todas as operações podem ser revertidas!
    Revise sempre este método após gerar uma migração.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_configuracao_distrito_id'), table_name='configuracao_distrito')
    op.drop_table('configuracao_distrito')
    # ### end Alembic commands ###
