"""add solicitacao_substituicao_emergencial table

Revision ID: 6737ac862e2e
Revises: 0002
Create Date: 2025-12-22 22:14:47.772528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Identificadores de revisão usados pelo Alembic
revision: str = '6737ac862e2e'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Aplica as mudanças da migração (upgrade).
    
    Este método é executado quando você roda:
    - alembic upgrade head (aplica todas as migrações pendentes)
    - alembic upgrade +1 (aplica a próxima migração)
    - alembic upgrade <revision> (aplica até uma revisão específica)
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitacao_substituicao_emergencial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitacao_troca_id', sa.Integer(), nullable=False),
    sa.Column('item_escala_id', sa.Integer(), nullable=False),
    sa.Column('substituto_emergencial_id', sa.Integer(), nullable=False),
    sa.Column('usuario_substituido_id', sa.Integer(), nullable=False),
    sa.Column('pastor_id', sa.Integer(), nullable=False),
    sa.Column('igreja_id', sa.Integer(), nullable=False),
    sa.Column('motivo_emergencia', sa.Text(), nullable=False),
    sa.Column('observacao_pastor', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDENTE', 'ACEITA', 'RECUSADA', name='statussubstituicaoemergencial'), nullable=False),
    sa.Column('tipo', sa.Text(), nullable=False),
    sa.Column('data_resposta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['igreja_id'], ['igreja.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_escala_id'], ['item_escala.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pastor_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['solicitacao_troca_id'], ['solicitacao_troca.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['substituto_emergencial_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_substituido_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solicitacao_substituicao_emergencial_id'), 'solicitacao_substituicao_emergencial', ['id'], unique=False)
    op.alter_column('distrito', 'config_recorrencia_maxima',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('distrito', 'config_intervalo_minimo',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('distrito', 'config_usa_preferencia',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('distrito', 'config_exige_confirmacao',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('distrito', 'config_prazo_confirmacao_horas',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('distrito', 'config_exige_aprovacao_troca',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('distrito', 'config_prazo_avaliacao_dias',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('distrito', 'status',
               existing_type=postgresql.ENUM('ATIVO', 'INATIVO', name='status_geral'),
               server_default=None,
               existing_nullable=True)
    op.alter_column('escala', 'status',
               existing_type=postgresql.ENUM('RASCUNHO', 'PUBLICADA', 'ARQUIVADA', name='status_escala'),
               server_default=None,
               existing_nullable=True)
    op.alter_column('historico_substituicao_emergencial', 'pontos_ganhos',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               server_default=None,
               existing_nullable=True)
    op.alter_column('horario_culto', 'ativo',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('horario_culto', 'aplicado_em_lote',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('igreja', 'status',
               existing_type=postgresql.ENUM('ATIVO', 'INATIVO', name='status_geral'),
               server_default=None,
               existing_nullable=True)
    op.alter_column('item_escala', 'status_confirmacao_pregador',
               existing_type=postgresql.ENUM('PENDENTE', 'CONFIRMADO', 'NAO_CONFIRMADO', name='statusconfirmacao'),
               server_default=None,
               existing_nullable=True)
    op.alter_column('item_escala', 'status_confirmacao_cantor',
               existing_type=postgresql.ENUM('PENDENTE', 'CONFIRMADO', 'NAO_CONFIRMADO', name='statusconfirmacao'),
               server_default=None,
               existing_nullable=True)
    op.alter_column('item_escala', 'status_realizacao',
               existing_type=postgresql.ENUM('PENDENTE', 'REALIZADO', 'CANCELADO', 'FALTA_PREGADOR', 'FALTA_CANTOR', name='statusrealizacao'),
               server_default=None,
               existing_nullable=True)
    op.alter_column('log_notificacao', 'tentativas',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('notificacao', 'lida',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('notificacao', 'enviada_email',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('notificacao', 'enviada_sms',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('notificacao', 'enviada_whatsapp',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.drop_constraint('organizacao_cnpj_key', 'organizacao', type_='unique')
    op.drop_index('ix_organizacao_cnpj', table_name='organizacao')
    op.create_index(op.f('ix_organizacao_cnpj'), 'organizacao', ['cnpj'], unique=True)
    op.alter_column('penalidade', 'data_aplicacao',
               existing_type=sa.DATE(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('penalidade', 'ativa',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('solicitacao_troca', 'status',
               existing_type=postgresql.ENUM('PENDENTE_SUBSTITUTO', 'PENDENTE_PASTOR', 'APROVADA', 'RECUSADA', name='statussolicitacaotroca'),
               server_default=None,
               existing_nullable=True)
    op.alter_column('tema', 'status',
               existing_type=postgresql.ENUM('ATIVO', 'INATIVO', name='status_geral'),
               server_default=None,
               existing_nullable=True)
    op.alter_column('usuario', 'score_atual',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               server_default=None,
               existing_nullable=True)
    op.alter_column('usuario', 'contador_mes_atual',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('usuario', 'contador_total_participacoes',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('usuario', 'contador_faltas',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('usuario', 'contador_desmarcacoes',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('usuario', 'pode_pregar',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('usuario', 'pode_cantar',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('usuario', 'status',
               existing_type=postgresql.ENUM('ATIVO', 'INATIVO', name='status_geral'),
               server_default=None,
               existing_nullable=True)
    op.alter_column('usuario', 'status_aprovacao',
               existing_type=postgresql.ENUM('PENDENTE_APROVACAO', 'APROVADO', 'RECUSADO', name='status_aprovacao'),
               server_default=None,
               existing_nullable=True)
    op.drop_constraint('usuario_cpf_key', 'usuario', type_='unique')
    op.drop_constraint('usuario_email_key', 'usuario', type_='unique')
    op.drop_index('ix_usuario_cpf', table_name='usuario')
    op.create_index(op.f('ix_usuario_cpf'), 'usuario', ['cpf'], unique=True)
    op.drop_index('ix_usuario_email', table_name='usuario')
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Reverte as mudanças da migração (downgrade).
    
    Este método é executado quando você roda:
    - alembic downgrade -1 (reverte a última migração)
    - alembic downgrade base (reverte todas as migrações)
    - alembic downgrade <revision> (reverte até uma revisão específica)
    
    ATENÇÃO: Nem todas as operações podem ser revertidas!
    Revise sempre este método após gerar uma migração.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.create_index('ix_usuario_email', 'usuario', ['email'], unique=False)
    op.drop_index(op.f('ix_usuario_cpf'), table_name='usuario')
    op.create_index('ix_usuario_cpf', 'usuario', ['cpf'], unique=False)
    op.create_unique_constraint('usuario_email_key', 'usuario', ['email'])
    op.create_unique_constraint('usuario_cpf_key', 'usuario', ['cpf'])
    op.alter_column('usuario', 'status_aprovacao',
               existing_type=postgresql.ENUM('PENDENTE_APROVACAO', 'APROVADO', 'RECUSADO', name='status_aprovacao'),
               server_default=sa.text("'APROVADO'::status_aprovacao"),
               existing_nullable=True)
    op.alter_column('usuario', 'status',
               existing_type=postgresql.ENUM('ATIVO', 'INATIVO', name='status_geral'),
               server_default=sa.text("'ATIVO'::status_geral"),
               existing_nullable=True)
    op.alter_column('usuario', 'pode_cantar',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('usuario', 'pode_pregar',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('usuario', 'contador_desmarcacoes',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('usuario', 'contador_faltas',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('usuario', 'contador_total_participacoes',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('usuario', 'contador_mes_atual',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('usuario', 'score_atual',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               server_default=sa.text('70.00'),
               existing_nullable=True)
    op.alter_column('tema', 'status',
               existing_type=postgresql.ENUM('ATIVO', 'INATIVO', name='status_geral'),
               server_default=sa.text("'ATIVO'::status_geral"),
               existing_nullable=True)
    op.alter_column('solicitacao_troca', 'status',
               existing_type=postgresql.ENUM('PENDENTE_SUBSTITUTO', 'PENDENTE_PASTOR', 'APROVADA', 'RECUSADA', name='statussolicitacaotroca'),
               server_default=sa.text("'PENDENTE_SUBSTITUTO'::statussolicitacaotroca"),
               existing_nullable=True)
    op.alter_column('penalidade', 'ativa',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('penalidade', 'data_aplicacao',
               existing_type=sa.DATE(),
               server_default=sa.text('CURRENT_DATE'),
               existing_nullable=False)
    op.drop_index(op.f('ix_organizacao_cnpj'), table_name='organizacao')
    op.create_index('ix_organizacao_cnpj', 'organizacao', ['cnpj'], unique=False)
    op.create_unique_constraint('organizacao_cnpj_key', 'organizacao', ['cnpj'])
    op.alter_column('notificacao', 'enviada_whatsapp',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('notificacao', 'enviada_sms',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('notificacao', 'enviada_email',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('notificacao', 'lida',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('log_notificacao', 'tentativas',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=True)
    op.alter_column('item_escala', 'status_realizacao',
               existing_type=postgresql.ENUM('PENDENTE', 'REALIZADO', 'CANCELADO', 'FALTA_PREGADOR', 'FALTA_CANTOR', name='statusrealizacao'),
               server_default=sa.text("'PENDENTE'::statusrealizacao"),
               existing_nullable=True)
    op.alter_column('item_escala', 'status_confirmacao_cantor',
               existing_type=postgresql.ENUM('PENDENTE', 'CONFIRMADO', 'NAO_CONFIRMADO', name='statusconfirmacao'),
               server_default=sa.text("'PENDENTE'::statusconfirmacao"),
               existing_nullable=True)
    op.alter_column('item_escala', 'status_confirmacao_pregador',
               existing_type=postgresql.ENUM('PENDENTE', 'CONFIRMADO', 'NAO_CONFIRMADO', name='statusconfirmacao'),
               server_default=sa.text("'PENDENTE'::statusconfirmacao"),
               existing_nullable=True)
    op.alter_column('igreja', 'status',
               existing_type=postgresql.ENUM('ATIVO', 'INATIVO', name='status_geral'),
               server_default=sa.text("'ATIVO'::status_geral"),
               existing_nullable=True)
    op.alter_column('horario_culto', 'aplicado_em_lote',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('horario_culto', 'ativo',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('historico_substituicao_emergencial', 'pontos_ganhos',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               server_default=sa.text('5.00'),
               existing_nullable=True)
    op.alter_column('escala', 'status',
               existing_type=postgresql.ENUM('RASCUNHO', 'PUBLICADA', 'ARQUIVADA', name='status_escala'),
               server_default=sa.text("'RASCUNHO'::status_escala"),
               existing_nullable=True)
    op.alter_column('distrito', 'status',
               existing_type=postgresql.ENUM('ATIVO', 'INATIVO', name='status_geral'),
               server_default=sa.text("'ATIVO'::status_geral"),
               existing_nullable=True)
    op.alter_column('distrito', 'config_prazo_avaliacao_dias',
               existing_type=sa.INTEGER(),
               server_default=sa.text('7'),
               existing_nullable=True)
    op.alter_column('distrito', 'config_exige_aprovacao_troca',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('distrito', 'config_prazo_confirmacao_horas',
               existing_type=sa.INTEGER(),
               server_default=sa.text('48'),
               existing_nullable=True)
    op.alter_column('distrito', 'config_exige_confirmacao',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('distrito', 'config_usa_preferencia',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('distrito', 'config_intervalo_minimo',
               existing_type=sa.INTEGER(),
               server_default=sa.text('7'),
               existing_nullable=True)
    op.alter_column('distrito', 'config_recorrencia_maxima',
               existing_type=sa.INTEGER(),
               server_default=sa.text('3'),
               existing_nullable=True)
    op.drop_index(op.f('ix_solicitacao_substituicao_emergencial_id'), table_name='solicitacao_substituicao_emergencial')
    op.drop_table('solicitacao_substituicao_emergencial')
    # ### end Alembic commands ###
